# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-11-18 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181118_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ImageField(null=True, upload_to=b'media', verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87'),
        ),
    ]
